#!/bin/sh
      
/usr/bin/invoke_app "$@" -C @tool/bin/cc3dbase4x.sh -t cc3dbase4x \
                         -u compucell3d-4.2.2 \
                         -w captive \
                         -r none 
                         
